name: MI-R4A-Padavan

on: 
  workflow_dispatch:

permissions:
  contents: write
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
        sudo timedatectl set-timezone Asia/Shanghai

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        version: latest
        install-only: true

    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

        ##### 小米R4A存储空间优化（原K2P配置修改）#####
        sed -i 's/size_etc="6M"/size_etc="3M"/g' /opt/rt-n56u/trunk/user/scripts/dev_init.sh
        sed -i 's/mtd_part_size=65536/mtd_part_size=3145728/g' /opt/rt-n56u/trunk/user/scripts/mtd_storage.sh

        ##### 加载设备配置文件（新增关键步骤）#####
        git clone https://github.com/hanwckf/rt-n56u-configs.git
        cp -r rt-n56u-configs/XIAOMI-R4A /opt/rt-n56u/trunk/configs/boards/

    - name: Build Firmware
      env:
        TNAME: MI-R4A  # 修改设备标识符
        KERNEL: 3.4
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
          echo "错误：缺少 $TNAME.config 配置文件"
          exit 1
        fi
        cp -f configs/templates/$TNAME.config .config

        ##### 功能配置（保留原K2P格式）#####
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        
        # 清除默认配置（保持原K2P清理逻辑）
        sed -i '/CONFIG_FIRMWARE_ENABLE_IPV6/d' .config
        [其余清理命令...]

        ##### 新增VNT功能（用户特别要求）#####
        echo "CONFIG_FIRMWARE_INCLUDE_VNTCLI=y" >> .config  # vnt客户端
        echo "CONFIG_FIRMWARE_INCLUDE_VNTS=y" >> .config    # vnt服务端
        echo "CONFIG_FIRMWARE_INCLUDE_TUN=y" >> .config     # TUN驱动支持

        ##### 编译执行（保持原K2P流程）#####
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
        cp -f .config /opt/images/${TNAME}.config

    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: MI-R4A-Build  # 修改产物名称
        path: /opt/images

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ### 小米R4A千兆版Padavan固件
          - 编译时间: ${{ env.build_time }}
          - 内核版本: 3.4.x
          - 包含功能: VNT组网/KVR漫游/SmartDNS
        tag_name: ${{ env.tag }}
        files: /opt/images/*
